# Generated by Django 3.0 on 2020-01-08 03:28

from django.db import migrations, models
import myapp.item.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('oily', models.CharField(default='', max_length=1)),
                ('dry', models.CharField(default='', max_length=1)),
                ('sensitive', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('category', models.CharField(max_length=15)),
                ('ingredients', models.TextField(max_length=300)),
                ('monthlySales', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to=myapp.item.models.thumbnail_path)),
                ('image', models.ImageField(upload_to=myapp.item.models.image_path)),
                ('image_id', models.CharField(max_length=32)),
            ],
        ),
    ]
