# Generated by Django 3.0 on 2020-01-08 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Constitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('oily', models.CharField(default='', max_length=1)),
                ('dry', models.CharField(default='', max_length=1)),
                ('sensitive', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('monthlySales', models.IntegerField()),
                ('image_id', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Category')),
                ('ingredient', models.ManyToManyField(through='item.Constitute', to='item.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='constitute',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Ingredient'),
        ),
        migrations.AddField(
            model_name='constitute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Product'),
        ),
    ]
